import type { PlaceSearchResult } from "./place-search-types";

export const localPlaceAliases: PlaceSearchResult[] = [
  {
    id: "local-quezon-city",
    provider: "local",
    aliases: ["kyusi", "qc", "quezon city"],
    name: "Quezon City",
    label: "Metro Manila, Philippines",
    lat: 14.676,
    lng: 121.0437,
    category: "City",
  },
  {
    id: "local-ust",
    provider: "local",
    aliases: ["ust", "university of santo tomas"],
    name: "University of Santo Tomas",
    label: "Sampaloc, Manila, Philippines",
    lat: 14.6099,
    lng: 120.9896,
    category: "University",
  },
  {
    id: "local-escolta",
    provider: "local",
    aliases: ["escolta"],
    name: "Escolta",
    label: "Binondo, Manila, Philippines",
    lat: 14.5986,
    lng: 120.9756,
    category: "Street / Historic area",
  },
  {
    id: "local-rizal-park",
    provider: "local",
    aliases: ["rizal park", "luneta"],
    name: "Rizal Park",
    label: "Ermita, Manila, Philippines",
    lat: 14.5826,
    lng: 120.9787,
    category: "Park",
  },
  {
    id: "local-tayuman",
    provider: "local",
    aliases: ["tayuman"],
    name: "Tayuman",
    label: "Manila, Philippines",
    lat: 14.6169,
    lng: 120.9827,
    category: "Area / Station",
  },
  {
    id: "local-intramuros",
    provider: "local",
    aliases: ["intramuros", "walled city"],
    name: "Intramuros",
    label: "Manila, Philippines",
    lat: 14.5896,
    lng: 120.9747,
    category: "Historic area",
  },
  {
    id: "local-quiapo",
    provider: "local",
    aliases: ["quiapo"],
    name: "Quiapo",
    label: "Manila, Philippines",
    lat: 14.5988,
    lng: 120.9836,
    category: "District",
  },
  {
    id: "local-recto",
    provider: "local",
    aliases: ["recto", "recto avenue"],
    name: "Recto Avenue",
    label: "Manila, Philippines",
    lat: 14.6038,
    lng: 120.9834,
    category: "Street / Station",
  },
];
